baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Maxim Russkikh resume'
theme="almeida-cv"

[params]
enableMetaTags = true
colorLight = "#FFFFE0"
colorDark = "#000000"
colorPageBackground = "#F8F8FF"
colorPrimary = "#A45A37"
colorSecondary = "#008B8B"
colorIconPrimary = "#7C523D"
colorIconBackground = "#A45A37"
colorRightColumnBackground = "#F5DEB3"
colorRightColumnHeadingText = "#000000"
colorRightColumnBodyText = "#000000"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#008B8B"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = true